### PR TITLE
Update code style for new php cs version

### PR DESCRIPTION
**Pull request by micgro42**
This should hopefully fix most of the issues found in #151

### CODE REVIEW

**Comment by micgro42** [comment]
Meh, for the last commit to pass, an update of the PHPUnit version is required, which in turn requires a new release of the DataValues/DataValues library, because we are inheriting from on of their test classes. This could either be a 2.4 release or a 3.0.0 release (see DataValues/DataValues#58 about that).

**Comment by itamargiv** [comment]
@micgro42 It turns out that the `expectedException` was not a CS violation after all. However, the CI is failing with php 7.4 due to language deprecation issues.

**Comment by micgro42** [comment]
> @micgro42 It turns out that the `expectedException` was not a CS violation after all. [...]

From the Travis CI logs of #151:

```
FILE: ...travis/build/wmde/Time/tests/ValueParsers/YearTimeParserTest.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 3 WARNINGS AFFECTING 3 LINES
----------------------------------------------------------------------
  18 | WARNING | Deprecated SPDX license identifier "GPL-2.0+", see
     |         | <https://spdx.org/licenses/>
     |         | (MediaWiki.Commenting.LicenseComment.DeprecatedLicenseTag)
 165 | WARNING | Do not use @expectedException, use
     |         | $this->expectException().
     |         | (MediaWiki.Commenting.PhpunitAnnotations.ForbiddenExpectedException)
 166 | WARNING | Do not use @expectedExceptionMessage, use
     |         | $this->expectExceptionMessage().
     |         | (MediaWiki.Commenting.PhpunitAnnotations.ForbiddenExpectedExceptionMessage)
----------------------------------------------------------------------
```

> [...]  However, the CI is failing with php 7.4 due to language deprecation issues.

Yes, that touches on what I mentioned in my comment above. We probably have to drop that commit as well and look into it separately. Work on that was already started in #149

**Comment by micgro42** [comment]
Dropped the commit about adding PHP7.4 to Travis. This branch should be green now :crossed_fingers:

**Comment by micgro42** [comment]
Closed because the commits were rebased on top of #151.

**Pull request closed without merging**
