### PR TITLE
Also test with PHP 7.2

### PR DESCRIPTION
**Pull request by manicki**

### CODE REVIEW

**Comment by Ladsgroup** [comment]
I can't merge the PR

**Comment by JeroenDeDauw** [comment]
y u no 7.3?

**Comment by AlaaSarhan** [comment]
can't merge PR either :thinking: @JeroenDeDauw @manicki  can you? maybe you can change some settings so that wmde team have the correct rights?

**Comment by JeroenDeDauw** [comment]
Pretty sure a certain Raz removed all permissions I had on anything in the WMDE org.

**Comment by manicki** [comment]
It was rather a certain @manicki who didn't set permissions right after this repo was transferred to wmde org. Will fix

**Comment by manicki** [comment]
> y u no 7.3?

I tried it for 20 seconds and PHPUnit didn't want to comply (the ancient version we use). I'll follow up on this.

**Pull request merged**
