### PR TITLE
Update wikibase-codesniffer to v1.2.0

### PR DESCRIPTION
**Pull request by chukarave**

### CODE REVIEW

**Review by toban — COMMENTED** [review]
Don't we need to fix the new issues that it's detecting now as well?

**Comment by mariushoch** [comment]
> Don't we need to fix the new issues that it's detecting now as well?

It needs to pass, but as a stopgap it might also be ok to just disable/ alter specific rules. The violations can probably be fixed within a couple of minutes, so I think that's probably best for this one.

**Comment by micgro42** [comment]
I created #151 to fix most of the issues, except for the line length issue. 100 characters seems a bit too little and also not aligned with what we have in other repositories or Wikibase.

**Comment by itamargiv** [comment]
@micgro42 why not increase it to 120 like we did in the [wikibase-vuejs-templating](https://github.com/wmde/php-vuejs-templating/pull/19) repository?

**Review by lucaswerkmeister — APPROVED** [review]
LGTM – I checked in code search that none of the `const`s made `private` here are used elsewhere. (If they are, and code search was missing some repositories, we can still make them public again in a patch release.)

**Pull request merged**
